// All PDF Tools Configuration
// iLovePDF-style RED color theme for all tools (consistent branding)
// Custom SVG icons for unique, professional branding

const RED_THEME = {
  color: '#e74c3c',      // Primary red (iLovePDF style)
  bg: '#fef2f2',         // Light red background
  accent: '#c0392b',     // Darker red for gradients
};

const GREEN_THEME = {
  color: '#27ae60',      // Green for optimize tools
  bg: '#e8f8f0',
  accent: '#1e8449',
};

const BLUE_THEME = {
  color: '#2980b9',      // Blue for security tools
  bg: '#ebf5fb',
  accent: '#1a5276',
};

const PURPLE_THEME = {
  color: '#8e44ad',      // Purple for edit tools
  bg: '#f5eef8',
  accent: '#6c3483',
};

// Custom SVG Icons - Unique designs for each tool
const ICONS = {
  // Organize PDF Icons
  merge: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="8" y="12" width="28" height="36" rx="3" stroke="currentColor" stroke-width="3" fill="none"/><rect x="28" y="16" width="28" height="36" rx="3" stroke="currentColor" stroke-width="3" fill="none" opacity="0.7"/><path d="M20 28 L20 36 M24 32 L16 32" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/><path d="M44 28 L44 36 M40 32 L48 32" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/></svg>`,
  split: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="18" y="8" width="28" height="48" rx="3" stroke="currentColor" stroke-width="3" fill="none"/><path d="M32 4 L32 60" stroke="currentColor" stroke-width="2.5" stroke-dasharray="4 3" stroke-linecap="round"/><path d="M24 24 L16 32 L24 40" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" fill="none"/><path d="M40 24 L48 32 L40 40" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" fill="none"/></svg>`,
  delete: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="12" y="10" width="40" height="44" rx="3" stroke="currentColor" stroke-width="3" fill="none"/><path d="M20 24 L44 40 M44 24 L20 40" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><circle cx="32" cy="32" r="22" stroke="currentColor" stroke-width="2" stroke-dasharray="3 3" fill="none"/></svg>`,
  extract: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="14" y="8" width="36" height="48" rx="3" stroke="currentColor" stroke-width="3" fill="none"/><rect x="28" y="28" width="24" height="28" rx="2" stroke="currentColor" stroke-width="2.5" fill="none"/><path d="M38 38 L38 48 L48 38" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
  reorder: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="16" y="10" width="32" height="14" rx="2" stroke="currentColor" stroke-width="2.5" fill="none"/><rect x="16" y="28" width="32" height="14" rx="2" stroke="currentColor" stroke-width="2.5" fill="none"/><rect x="16" y="46" width="32" height="14" rx="2" stroke="currentColor" stroke-width="2.5" fill="none"/><path d="M52 32 L58 35 L52 38" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M12 32 L6 35 L12 38" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
  scan: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="10" y="14" width="44" height="36" rx="4" stroke="currentColor" stroke-width="3" fill="none"/><circle cx="32" cy="32" r="10" stroke="currentColor" stroke-width="2.5" fill="none"/><path d="M32 18 L32 22 M32 42 L32 46 M18 32 L22 32 M42 32 L46 32" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/><path d="M16 24 L24 16" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/></svg>`,
  
  // Optimize PDF Icons
  compress: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="16" y="12" width="32" height="40" rx="3" stroke="currentColor" stroke-width="3" fill="none"/><path d="M24 44 L32 52 L40 44" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M24 20 L32 12 L40 20" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/><line x1="32" y1="12" x2="32" y2="52" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/></svg>`,
  repair: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="14" y="10" width="36" height="44" rx="3" stroke="currentColor" stroke-width="3" fill="none"/><path d="M32 18 L32 30 M32 46 L32 38" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><circle cx="32" cy="34" r="8" stroke="currentColor" stroke-width="2.5" fill="none"/><path d="M44 20 L54 14 M50 10 L56 16" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/><rect x="46" y="12" width="8" height="12" rx="2" stroke="currentColor" stroke-width="2" fill="none"/></svg>`,
  ocr: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="12" y="10" width="40" height="44" rx="3" stroke="currentColor" stroke-width="3" fill="none"/><circle cx="32" cy="32" r="14" stroke="currentColor" stroke-width="2.5" fill="none"/><path d="M42 42 L52 52" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><text x="24" y="37" fontSize="12" fontWeight="bold" fill="currentColor" stroke="none">Aa</text></svg>`,
  
  // Convert to PDF Icons
  jpgToPdf: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="10" y="12" width="28" height="40" rx="3" stroke="currentColor" stroke-width="3" fill="none"/><circle cx="24" cy="28" r="6" stroke="currentColor" stroke-width="2" fill="none"/><path d="M18 38 L24 32 L30 38" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none"/><rect x="36" y="16" width="20" height="32" rx="2" stroke="currentColor" stroke-width="2.5" fill="none" opacity="0.6"/><path d="M42 28 L46 32 L50 26" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
  wordToPdf: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="12" y="10" width="26" height="44" rx="2" stroke="currentColor" stroke-width="2.5" fill="none"/><text x="18" y="38" fontSize="14" fontWeight="bold" fill="currentColor" stroke="none">W</text><path d="M42 32 L54 32" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><rect x="38" y="14" width="18" height="36" rx="2" stroke="currentColor" stroke-width="2.5" fill="none"/><path d="M42 26 L50 26 M42 34 L48 34 M42 42 L46 42" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>`,
  pptToPdf: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="10" y="14" width="36" height="28" rx="2" stroke="currentColor" stroke-width="2.5" fill="none"/><circle cx="28" cy="28" r="6" stroke="currentColor" stroke-width="2" fill="none"/><path d="M24 28 L28 24 L32 28 L28 32 Z" stroke="currentColor" stroke-width="1.5" fill="none"/><rect x="38" y="18" width="18" height="32" rx="2" stroke="currentColor" stroke-width="2.5" fill="none"/><text x="44" y="40" fontSize="12" fontWeight="bold" fill="currentColor" stroke="none">P</text></svg>`,
  excelToPdf: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="12" y="10" width="26" height="44" rx="2" stroke="currentColor" stroke-width="2.5" fill="none"/><line x1="18" y1="22" x2="32" y2="22" stroke="currentColor" stroke-width="1.5"/><line x1="18" y1="30" x2="32" y2="30" stroke="currentColor" stroke-width="1.5"/><line x1="18" y1="38" x2="32" y2="38" stroke="currentColor" stroke-width="1.5"/><rect x="38" y="16" width="18" height="32" rx="2" stroke="currentColor" stroke-width="2.5" fill="none"/><text x="44" y="38" fontSize="14" fontWeight="bold" fill="currentColor" stroke="none">X</text></svg>`,
  htmlToPdf: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="10" y="12" width="44" height="40" rx="3" stroke="currentColor" stroke-width="2.5" fill="none"/><path d="M18 24 L46 24" stroke="currentColor" stroke-width="2" stroke-linecap="round"/><text x="20" y="44" fontSize="10" fontWeight="bold" fill="currentColor" stroke="none">&lt;/&gt;</text><rect x="38" y="28" width="18" height="20" rx="2" stroke="currentColor" stroke-width="2" fill="none" opacity="0.7"/></svg>`,
  
  // Convert from PDF Icons
  pdfToJpg: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="14" y="10" width="28" height="44" rx="3" stroke="currentColor" stroke-width="3" fill="none"/><rect x="32" y="18" width="24" height="20" rx="2" stroke="currentColor" stroke-width="2.5" fill="none"/><circle cx="44" cy="28" r="5" stroke="currentColor" stroke-width="2" fill="none"/><path d="M38 34 L44 28 L50 34" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none"/><path d="M46 44 L54 52" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/></svg>`,
  pdfToWord: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="14" y="10" width="28" height="44" rx="3" stroke="currentColor" stroke-width="3" fill="none"/><path d="M46 24 L58 24 L58 50 L46 50 Z" stroke="currentColor" stroke-width="2.5" fill="none"/><text x="50" y="42" fontSize="12" fontWeight="bold" fill="currentColor" stroke="none">W</text><path d="M28 36 L42 36" stroke="currentColor" stroke-width="2" stroke-linecap="round"/><path d="M28 42 L38 42" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>`,
  pdfToPpt: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="14" y="12" width="28" height="40" rx="3" stroke="currentColor" stroke-width="3" fill="none"/><rect x="36" y="18" width="22" height="16" rx="2" stroke="currentColor" stroke-width="2.5" fill="none"/><circle cx="47" cy="26" r="4" stroke="currentColor" stroke-width="1.5" fill="none"/><path d="M44 26 L47 23 L50 26 L47 29 Z" stroke="currentColor" stroke-width="1" fill="none"/><path d="M46 38 L54 46" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/></svg>`,
  pdfToExcel: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="14" y="10" width="28" height="44" rx="3" stroke="currentColor" stroke-width="3" fill="none"/><rect x="36" y="16" width="22" height="32" rx="2" stroke="currentColor" stroke-width="2.5" fill="none"/><line x1="40" y1="24" x2="54" y2="24" stroke="currentColor" stroke-width="1.5"/><line x1="40" y1="30" x2="54" y2="30" stroke="currentColor" stroke-width="1.5"/><line x1="40" y1="36" x2="54" y2="36" stroke="currentColor" stroke-width="1.5"/><text x="42" y="44" fontSize="10" fontWeight="bold" fill="currentColor" stroke="none">X</text></svg>`,
  pdfToPdfa: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="16" y="10" width="28" height="44" rx="3" stroke="currentColor" stroke-width="3" fill="none"/><rect x="24" y="24" width="24" height="24" rx="2" stroke="currentColor" stroke-width="2.5" fill="none"/><text x="30" y="42" fontSize="14" fontWeight="bold" fill="currentColor" stroke="none">A</text><path d="M50 14 L56 14 L56 50 L50 50" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none"/></svg>`,
  
  // Edit PDF Icons
  rotate: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="18" y="14" width="28" height="36" rx="3" stroke="currentColor" stroke-width="3" fill="none"/><path d="M46 24 C54 28, 54 44, 46 48" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" fill="none"/><path d="M42 20 L46 24 L50 20" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M50 44 L46 48 L42 44" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/><circle cx="32" cy="32" r="6" stroke="currentColor" stroke-width="2" stroke-dasharray="2 2" fill="none"/></svg>`,
  addNumbers: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="14" y="10" width="36" height="44" rx="3" stroke="currentColor" stroke-width="3" fill="none"/><text x="22" y="32" fontSize="14" fontWeight="bold" fill="currentColor" stroke="none">1</text><text x="32" y="32" fontSize="14" fontWeight="bold" fill="currentColor" stroke="none">2</text><text x="42" y="32" fontSize="14" fontWeight="bold" fill="currentColor" stroke="none">3</text><line x1="20" y1="44" x2="44" y2="44" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>`,
  watermark: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="14" y="10" width="36" height="44" rx="3" stroke="currentColor" stroke-width="3" fill="none"/><path d="M20 32 L44 32" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-dasharray="3 3"/><path d="M20 40 L44 40" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-dasharray="3 3"/><circle cx="46" cy="22" r="10" stroke="currentColor" stroke-width="2.5" fill="none"/><path d="M43 19 L49 25 M49 19 L43 25" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>`,
  crop: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="16" width="28" height="32" rx="2" stroke="currentColor" stroke-width="2.5" fill="none"/><path d="M14 24 L20 24 L20 18" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><path d="M50 40 L44 40 L44 46" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><path d="M14 40 L20 40 L20 46" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><path d="M50 24 L44 24 L44 18" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
  edit: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="14" y="10" width="36" height="44" rx="3" stroke="currentColor" stroke-width="3" fill="none"/><path d="M42 24 L54 12 L58 16 L46 28 L42 28 Z" stroke="currentColor" stroke-width="2.5" fill="none" stroke-linecap="round" stroke-linejoin="round"/><path d="M48 20 L52 24" stroke="currentColor" stroke-width="2" stroke-linecap="round"/><line x1="22" y1="34" x2="36" y2="34" stroke="currentColor" stroke-width="2" stroke-linecap="round"/><line x1="22" y1="42" x2="32" y2="42" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>`,
  
  // Security PDF Icons
  unlock: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="16" y="26" width="32" height="28" rx="3" stroke="currentColor" stroke-width="3" fill="none"/><path d="M26 26 L26 20 C26 14, 38 14, 38 20 L38 24" stroke="currentColor" stroke-width="3" stroke-linecap="round" fill="none"/><circle cx="32" cy="40" r="5" stroke="currentColor" stroke-width="2.5" fill="none"/><path d="M32 37 L32 43 M29 40 L35 40" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/><path d="M52 20 L58 14" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/></svg>`,
  protect: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M32 8 L50 18 L50 36 C50 48, 32 58, 32 58 C32 58, 14 48, 14 36 L14 18 Z" stroke="currentColor" stroke-width="3" fill="none"/><circle cx="32" cy="34" r="8" stroke="currentColor" stroke-width="2.5" fill="none"/><path d="M32 31 L32 37 M29 34 L35 34" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/></svg>`,
  sign: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="12" y="14" width="40" height="36" rx="3" stroke="currentColor" stroke-width="3" fill="none"/><path d="M20 38 C24 34, 28 42, 32 36 C36 30, 40 38, 44 34" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" fill="none"/><path d="M48 24 L56 16 L60 20 L52 28" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" fill="none"/><circle cx="54" cy="22" r="4" stroke="currentColor" stroke-width="2" fill="none"/></svg>`,
  redact: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="14" y="10" width="36" height="44" rx="3" stroke="currentColor" stroke-width="3" fill="none"/><rect x="20" y="24" width="24" height="12" rx="2" stroke="currentColor" stroke-width="2" fill="currentColor" opacity="0.3"/><line x1="18" y1="30" x2="46" y2="30" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><path d="M50 18 L58 26 M58 18 L50 26" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/></svg>`,
  compare: `<svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="10" y="14" width="26" height="36" rx="3" stroke="currentColor" stroke-width="2.5" fill="none" opacity="0.7"/><rect x="28" y="14" width="26" height="36" rx="3" stroke="currentColor" stroke-width="2.5" fill="none"/><path d="M24 32 L40 32" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/><path d="M36 26 L42 32 L36 38" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none"/><path d="M28 26 L22 32 L28 38" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none"/></svg>`,
};

export const TOOL_GROUPS = [
  {
    name: 'Organize PDF',
    tools: [
      {
        id: 'merge-pdf',
        title: 'Merge PDF',
        description: 'Combine multiple PDF files into one document in the order you choose.',
        icon: ICONS.merge,
        glyph: '⇄',
        color: RED_THEME.color,
        bg: RED_THEME.bg,
        href: '/merge-pdf',
        keywords: ['combine', 'join', 'merge', 'pdf'],
        processing: 'client',
      },
      {
        id: 'split-pdf',
        title: 'Split PDF',
        description: 'Separate one PDF into multiple files or extract specific pages.',
        icon: ICONS.split,
        glyph: '↘',
        color: RED_THEME.color,
        bg: RED_THEME.bg,
        href: '/split-pdf',
        keywords: ['split', 'extract', 'separate', 'pages'],
        processing: 'client',
      },
      {
        id: 'delete-pages',
        title: 'Remove pages',
        description: 'Remove unwanted pages from your PDF file.',
        icon: ICONS.delete,
        glyph: '−',
        color: RED_THEME.color,
        bg: RED_THEME.bg,
        href: '/delete-pages',
        keywords: ['delete', 'remove', 'pages'],
        processing: 'client',
      },
      {
        id: 'extract-pages',
        title: 'Extract pages',
        description: 'Extract specific pages from your PDF and save them as a new file.',
        icon: ICONS.extract,
        glyph: '↗',
        color: RED_THEME.color,
        bg: RED_THEME.bg,
        href: '/extract-pages',
        keywords: ['extract', 'pages', 'select'],
        processing: 'client',
      },
      {
        id: 'reorder-pages',
        title: 'Organize PDF',
        description: 'Rearrange the order of pages in your PDF document.',
        icon: ICONS.reorder,
        glyph: '↕',
        color: RED_THEME.color,
        bg: RED_THEME.bg,
        href: '/reorder-pages',
        keywords: ['reorder', 'rearrange', 'pages', 'order', 'organize'],
        processing: 'client',
      },
      {
        id: 'scan-to-pdf',
        title: 'Scan to PDF',
        description: 'Use your camera or scanner to create PDF documents.',
        icon: ICONS.scan,
        glyph: '📷',
        color: RED_THEME.color,
        bg: RED_THEME.bg,
        href: '/scan-to-pdf',
        keywords: ['scan', 'camera', 'scanner'],
        processing: 'client',
      },
    ],
  },
  {
    name: 'Optimize PDF',
    tools: [
      {
        id: 'compress-pdf',
        title: 'Compress PDF',
        description: 'Reduce PDF file size while optimizing for maximum quality.',
        icon: ICONS.compress,
        glyph: '⤢',
        color: GREEN_THEME.color,
        bg: GREEN_THEME.bg,
        href: '/compress-pdf',
        keywords: ['compress', 'reduce', 'optimize', 'size'],
        processing: 'client',
      },
      {
        id: 'repair-pdf',
        title: 'Repair PDF',
        description: 'Fix corrupted or damaged PDF files and recover content.',
        icon: ICONS.repair,
        glyph: '🔧',
        color: GREEN_THEME.color,
        bg: GREEN_THEME.bg,
        href: '/repair-pdf',
        keywords: ['repair', 'fix', 'corrupted', 'damaged', 'recover'],
        processing: 'server',
      },
      {
        id: 'ocr-pdf',
        title: 'OCR PDF',
        description: 'Convert scanned PDFs into searchable and selectable text documents.',
        icon: ICONS.ocr,
        glyph: 'OCR',
        color: GREEN_THEME.color,
        bg: GREEN_THEME.bg,
        href: '/ocr-pdf',
        keywords: ['ocr', 'scan', 'text', 'recognize', 'searchable'],
        processing: 'server',
      },
    ],
  },
  {
    name: 'Convert to PDF',
    tools: [
      {
        id: 'jpg-to-pdf',
        title: 'JPG to PDF',
        description: 'Convert JPG, PNG, or other image files to PDF.',
        icon: ICONS.jpgToPdf,
        glyph: 'JPG',
        color: RED_THEME.color,
        bg: RED_THEME.bg,
        href: '/jpg-to-pdf',
        keywords: ['jpg', 'png', 'image', 'photo', 'convert'],
        processing: 'client',
      },
      {
        id: 'word-to-pdf',
        title: 'WORD to PDF',
        description: 'Convert your DOC and DOCX files to PDF format instantly.',
        icon: ICONS.wordToPdf,
        glyph: 'W',
        color: RED_THEME.color,
        bg: RED_THEME.bg,
        href: '/word-to-pdf',
        keywords: ['word', 'doc', 'docx', 'convert'],
        processing: 'server',
      },
      {
        id: 'ppt-to-pdf',
        title: 'POWERPOINT to PDF',
        description: 'Convert your PowerPoint presentations to PDF.',
        icon: ICONS.pptToPdf,
        glyph: 'P',
        color: RED_THEME.color,
        bg: RED_THEME.bg,
        href: '/ppt-to-pdf',
        keywords: ['powerpoint', 'pptx', 'slides', 'convert'],
        processing: 'server',
      },
      {
        id: 'excel-to-pdf',
        title: 'EXCEL to PDF',
        description: 'Turn Microsoft Excel spreadsheets into PDF documents.',
        icon: ICONS.excelToPdf,
        glyph: 'X',
        color: RED_THEME.color,
        bg: RED_THEME.bg,
        href: '/excel-to-pdf',
        keywords: ['excel', 'xlsx', 'spreadsheet', 'convert'],
        processing: 'server',
      },
      {
        id: 'html-to-pdf',
        title: 'HTML to PDF',
        description: 'Convert any web page URL or HTML content to PDF.',
        icon: ICONS.htmlToPdf,
        glyph: '</>',
        color: RED_THEME.color,
        bg: RED_THEME.bg,
        href: '/html-to-pdf',
        keywords: ['html', 'webpage', 'url', 'convert'],
        processing: 'server',
      },
    ],
  },
  {
    name: 'Convert from PDF',
    tools: [
      {
        id: 'pdf-to-jpg',
        title: 'PDF to JPG',
        description: 'Extract PDF pages as JPG images or convert to single pages.',
        icon: ICONS.pdfToJpg,
        glyph: 'JPG',
        color: RED_THEME.color,
        bg: RED_THEME.bg,
        href: '/pdf-to-jpg',
        keywords: ['pdf', 'jpg', 'png', 'image', 'extract'],
        processing: 'client',
      },
      {
        id: 'pdf-to-word',
        title: 'PDF to WORD',
        description: 'Convert your PDF to editable DOCX documents easily.',
        icon: ICONS.pdfToWord,
        glyph: 'W',
        color: RED_THEME.color,
        bg: RED_THEME.bg,
        href: '/pdf-to-word',
        keywords: ['pdf', 'word', 'docx', 'convert', 'editable'],
        processing: 'server',
      },
      {
        id: 'pdf-to-ppt',
        title: 'PDF to POWERPOINT',
        description: 'Convert PDF presentations into editable PowerPoint files.',
        icon: ICONS.pdfToPpt,
        glyph: 'P',
        color: RED_THEME.color,
        bg: RED_THEME.bg,
        href: '/pdf-to-ppt',
        keywords: ['pdf', 'powerpoint', 'pptx', 'slides', 'convert'],
        processing: 'server',
      },
      {
        id: 'pdf-to-excel',
        title: 'PDF to EXCEL',
        description: 'Extract tables and data from PDF into Excel spreadsheets.',
        icon: ICONS.pdfToExcel,
        glyph: 'X',
        color: RED_THEME.color,
        bg: RED_THEME.bg,
        href: '/pdf-to-excel',
        keywords: ['pdf', 'excel', 'xlsx', 'table', 'convert'],
        processing: 'server',
      },
      {
        id: 'pdf-to-pdfa',
        title: 'PDF to PDF/A',
        description: 'Convert PDF to PDF/A format for long-term archiving.',
        icon: ICONS.pdfToPdfa,
        glyph: 'A',
        color: RED_THEME.color,
        bg: RED_THEME.bg,
        href: '/pdf-to-pdfa',
        keywords: ['pdf', 'pdfa', 'archive', 'convert'],
        processing: 'server',
      },
    ],
  },
  {
    name: 'Edit PDF',
    tools: [
      {
        id: 'rotate-pdf',
        title: 'Rotate PDF',
        description: 'Rotate PDF pages to portrait or landscape orientation.',
        icon: ICONS.rotate,
        glyph: '↻',
        color: PURPLE_THEME.color,
        bg: PURPLE_THEME.bg,
        href: '/rotate-pdf',
        keywords: ['rotate', 'flip', 'orientation'],
        processing: 'client',
      },
      {
        id: 'add-page-numbers',
        title: 'Add page numbers',
        description: 'Add page numbers to your PDF in multiple positions and styles.',
        icon: ICONS.addNumbers,
        glyph: '#',
        color: PURPLE_THEME.color,
        bg: PURPLE_THEME.bg,
        href: '/add-page-numbers',
        keywords: ['page numbers', 'footer', 'header', 'numbering'],
        processing: 'client',
      },
      {
        id: 'watermark-pdf',
        title: 'Add watermark',
        description: 'Add text or image watermarks to protect your PDF documents.',
        icon: ICONS.watermark,
        glyph: 'WM',
        color: PURPLE_THEME.color,
        bg: PURPLE_THEME.bg,
        href: '/watermark-pdf',
        keywords: ['watermark', 'stamp', 'protect', 'branding'],
        processing: 'client',
      },
      {
        id: 'crop-pdf',
        title: 'Crop PDF',
        description: 'Remove unwanted margins or areas from PDF pages.',
        icon: ICONS.crop,
        glyph: '⊡',
        color: PURPLE_THEME.color,
        bg: PURPLE_THEME.bg,
        href: '/crop-pdf',
        keywords: ['crop', 'trim', 'cut', 'margins'],
        processing: 'client',
      },
      {
        id: 'edit-pdf',
        title: 'Edit PDF',
        description: 'Edit text, images, and other content in your PDF files.',
        icon: ICONS.edit,
        glyph: '✏️',
        color: PURPLE_THEME.color,
        bg: PURPLE_THEME.bg,
        href: '/edit-pdf',
        keywords: ['edit', 'text', 'images', 'modify'],
        processing: 'server',
      },
    ],
  },
  {
    name: 'PDF Security',
    tools: [
      {
        id: 'unlock-pdf',
        title: 'Unlock PDF',
        description: 'Remove password protection from PDF files you own.',
        icon: ICONS.unlock,
        glyph: '🔓',
        color: BLUE_THEME.color,
        bg: BLUE_THEME.bg,
        href: '/unlock-pdf',
        keywords: ['unlock', 'password', 'remove', 'protect'],
        processing: 'server',
      },
      {
        id: 'protect-pdf',
        title: 'Protect PDF',
        description: 'Add password encryption to secure your PDF documents.',
        icon: ICONS.protect,
        glyph: '🔒',
        color: BLUE_THEME.color,
        bg: BLUE_THEME.bg,
        href: '/protect-pdf',
        keywords: ['protect', 'password', 'encrypt', 'secure'],
        processing: 'client',
      },
      {
        id: 'sign-pdf',
        title: 'Sign PDF',
        description: 'Add digital signatures to your PDF documents.',
        icon: ICONS.sign,
        glyph: '✍️',
        color: BLUE_THEME.color,
        bg: BLUE_THEME.bg,
        href: '/sign-pdf',
        keywords: ['sign', 'signature', 'digital', 'sign'],
        processing: 'client',
      },
      {
        id: 'redact-pdf',
        title: 'Redact PDF',
        description: 'Permanently remove sensitive information from PDF files.',
        icon: ICONS.redact,
        glyph: '⬛',
        color: BLUE_THEME.color,
        bg: BLUE_THEME.bg,
        href: '/redact-pdf',
        keywords: ['redact', 'blackout', 'hide', 'sensitive', 'remove'],
        processing: 'server',
      },
      {
        id: 'compare-pdf',
        title: 'Compare PDF',
        description: 'Compare two PDF files and highlight the differences.',
        icon: ICONS.compare,
        glyph: '⚖️',
        color: BLUE_THEME.color,
        bg: BLUE_THEME.bg,
        href: '/compare-pdf',
        keywords: ['compare', 'difference', 'changes', 'versions'],
        processing: 'server',
      },
    ],
  },
];

export const ALL_TOOLS = TOOL_GROUPS.flatMap(g => g.tools);

export function getToolById(id) {
  return ALL_TOOLS.find(t => t.id === id);
}
