// All PDF Tools Configuration
// Color themes for tool icons

export const TOOL_GROUPS = [
  {
    name: 'Organize PDF',
    tools: [
      {
        id: 'merge-pdf',
        title: 'Merge PDF',
        description: 'Combine multiple PDF files into one document in the order you choose.',
        icon: '📄',
        color: '#3b82f6',
        bg: '#eff6ff',
        href: '/merge-pdf',
        keywords: ['combine', 'join', 'merge', 'pdf'],
        processing: 'client',
      },
      {
        id: 'split-pdf',
        title: 'Split PDF',
        description: 'Separate one PDF into multiple files or extract specific pages.',
        icon: '✂️',
        color: '#8b5cf6',
        bg: '#f5f3ff',
        href: '/split-pdf',
        keywords: ['split', 'extract', 'separate', 'pages'],
        processing: 'client',
      },
      {
        id: 'compress-pdf',
        title: 'Compress PDF',
        description: 'Reduce PDF file size while optimizing for maximum quality.',
        icon: '🗜️',
        color: '#10b981',
        bg: '#ecfdf5',
        href: '/compress-pdf',
        keywords: ['compress', 'reduce', 'optimize', 'size'],
        processing: 'client',
      },
      {
        id: 'rotate-pdf',
        title: 'Rotate PDF',
        description: 'Rotate PDF pages to portrait or landscape orientation.',
        icon: '🔄',
        color: '#f97316',
        bg: '#fff7ed',
        href: '/rotate-pdf',
        keywords: ['rotate', 'flip', 'orientation'],
        processing: 'client',
      },
      {
        id: 'delete-pages',
        title: 'Delete Pages',
        description: 'Remove unwanted pages from your PDF file.',
        icon: '🗑️',
        color: '#ef4444',
        bg: '#fef2f2',
        href: '/delete-pages',
        keywords: ['delete', 'remove', 'pages'],
        processing: 'client',
      },
      {
        id: 'reorder-pages',
        title: 'Reorder Pages',
        description: 'Rearrange the order of pages in your PDF document.',
        icon: '↕️',
        color: '#6366f1',
        bg: '#eef2ff',
        href: '/reorder-pages',
        keywords: ['reorder', 'rearrange', 'pages', 'order'],
        processing: 'client',
      },
    ],
  },
  {
    name: 'Convert to PDF',
    tools: [
      {
        id: 'word-to-pdf',
        title: 'Word to PDF',
        description: 'Convert your DOC and DOCX files to PDF format instantly.',
        icon: '📝',
        color: '#2563eb',
        bg: '#eff6ff',
        href: '/word-to-pdf',
        keywords: ['word', 'doc', 'docx', 'convert'],
        processing: 'server',
      },
      {
        id: 'excel-to-pdf',
        title: 'Excel to PDF',
        description: 'Turn Microsoft Excel spreadsheets into PDF documents.',
        icon: '📊',
        color: '#16a34a',
        bg: '#f0fdf4',
        href: '/excel-to-pdf',
        keywords: ['excel', 'xlsx', 'spreadsheet', 'convert'],
        processing: 'server',
      },
      {
        id: 'ppt-to-pdf',
        title: 'PowerPoint to PDF',
        description: 'Convert your PowerPoint presentations to PDF.',
        icon: '📽️',
        color: '#dc2626',
        bg: '#fef2f2',
        href: '/ppt-to-pdf',
        keywords: ['powerpoint', 'pptx', 'slides', 'convert'],
        processing: 'server',
      },
      {
        id: 'jpg-to-pdf',
        title: 'JPG to PDF',
        description: 'Convert JPG, PNG, or other image files to PDF.',
        icon: '🖼️',
        color: '#f59e0b',
        bg: '#fffbeb',
        href: '/jpg-to-pdf',
        keywords: ['jpg', 'png', 'image', 'photo', 'convert'],
        processing: 'client',
      },
      {
        id: 'html-to-pdf',
        title: 'HTML to PDF',
        description: 'Convert any web page URL or HTML content to PDF.',
        icon: '🌐',
        color: '#0891b2',
        bg: '#ecfeff',
        href: '/html-to-pdf',
        keywords: ['html', 'webpage', 'url', 'convert'],
        processing: 'server',
      },
    ],
  },
  {
    name: 'Convert from PDF',
    tools: [
      {
        id: 'pdf-to-word',
        title: 'PDF to Word',
        description: 'Convert your PDF to editable DOCX documents easily.',
        icon: '📄',
        color: '#2563eb',
        bg: '#eff6ff',
        href: '/pdf-to-word',
        keywords: ['pdf', 'word', 'docx', 'convert', 'editable'],
        processing: 'server',
      },
      {
        id: 'pdf-to-excel',
        title: 'PDF to Excel',
        description: 'Extract tables and data from PDF into Excel spreadsheets.',
        icon: '📋',
        color: '#16a34a',
        bg: '#f0fdf4',
        href: '/pdf-to-excel',
        keywords: ['pdf', 'excel', 'xlsx', 'table', 'convert'],
        processing: 'server',
      },
      {
        id: 'pdf-to-jpg',
        title: 'PDF to JPG',
        description: 'Extract PDF pages as JPG images or convert to single pages.',
        icon: '🖼️',
        color: '#f59e0b',
        bg: '#fffbeb',
        href: '/pdf-to-jpg',
        keywords: ['pdf', 'jpg', 'png', 'image', 'extract'],
        processing: 'client',
      },
    ],
  },
  {
    name: 'Edit & Secure PDF',
    tools: [
      {
        id: 'watermark-pdf',
        title: 'Watermark PDF',
        description: 'Add text or image watermarks to protect your PDF documents.',
        icon: '💧',
        color: '#0ea5e9',
        bg: '#f0f9ff',
        href: '/watermark-pdf',
        keywords: ['watermark', 'stamp', 'protect', 'branding'],
        processing: 'client',
      },
      {
        id: 'add-page-numbers',
        title: 'Add Page Numbers',
        description: 'Add page numbers to your PDF in multiple positions and styles.',
        icon: '🔢',
        color: '#7c3aed',
        bg: '#f5f3ff',
        href: '/add-page-numbers',
        keywords: ['page numbers', 'footer', 'header', 'numbering'],
        processing: 'client',
      },
      {
        id: 'protect-pdf',
        title: 'Protect PDF',
        description: 'Add a password to your PDF to prevent unauthorized access.',
        icon: '🔒',
        color: '#dc2626',
        bg: '#fef2f2',
        href: '/protect-pdf',
        keywords: ['protect', 'password', 'encrypt', 'secure'],
        processing: 'client',
      },
      {
        id: 'unlock-pdf',
        title: 'Unlock PDF',
        description: 'Remove password protection from your PDF files.',
        icon: '🔓',
        color: '#059669',
        bg: '#ecfdf5',
        href: '/unlock-pdf',
        keywords: ['unlock', 'decrypt', 'remove password'],
        processing: 'client',
      },
    ],
  },
];

export const ALL_TOOLS = TOOL_GROUPS.flatMap(g => g.tools);

export function getToolById(id) {
  return ALL_TOOLS.find(t => t.id === id);
}
